[IG]
#ig = fsh-generated/resources/ImplementationGuide-lacpass.racsel.org.json
#template = fhir.base.template#current

ig = fsh-generated/resources/ImplementationGuide-racsel.org.json
template = #template_RACSEL